# Generated by Django 2.0.1 on 2018-06-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=400, verbose_name='Registered Business Name')),
                ('con_name', models.CharField(max_length=300, verbose_name='Name of Contact')),
                ('con_email', models.CharField(max_length=300, verbose_name='Name of Contact Number')),
                ('reg_success', models.BooleanField(default=False)),
                ('address', models.TextField(blank=True, null=True)),
                ('acra', models.CharField(blank=True, max_length=50, null=True, verbose_name='ACRA Number')),
                ('con_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
