# Generated by Django 2.0.1 on 2018-06-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('florists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='reg_success',
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.IntegerField(choices=[(1, 'Live'), (2, 'Offline'), (3, 'Deactivated')], default=3),
        ),
    ]
