# Generated by Django 2.0.1 on 2018-06-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('florists', '0004_auto_20180615_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.IntegerField(choices=[(1, 'Live'), (2, 'Offline'), (3, 'Deactivated'), (4, 'Signup')], default=4),
        ),
    ]
