# Generated by Django 2.0.1 on 2018-06-16 23:48

from django.db import migrations
import florists.models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('florists', '0005_auto_20180617_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='banner',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=florists.models.gen_file_name),
        ),
        migrations.AddField(
            model_name='client',
            name='logo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=florists.models.gen_file_name),
        ),
    ]
