# Generated by Django 2.0.1 on 2018-07-14 07:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('florists', '0006_auto_20180617_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=[], size=None),
        ),
        migrations.AddField(
            model_name='client',
            name='hours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
        ),
    ]
