# Generated by Django 2.0.1 on 2018-07-14 07:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('florists', '0007_auto_20180714_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='questions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
        ),
    ]
