# Generated by Django 2.0.1 on 2018-06-20 00:06

from django.db import migrations, models
import gallery.models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('florists', '0006_auto_20180617_0748'),
    ]

    operations = [
        migrations.CreateModel(
            name='FImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=50, null=True, verbose_name='UUID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=gallery.models.gen_file_name)),
                ('img_main', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=gallery.models.gen_file_name_thumb)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete='CASCADE', to='florists.Client')),
            ],
        ),
    ]
