# Generated by Django 2.0.1 on 2018-06-15 03:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('florists', '0004_auto_20180615_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='FProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cli', models.ForeignKey(on_delete='CASCADE', to='florists.Client')),
                ('user', models.OneToOneField(on_delete='CASCADE', related_name='fprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
