# Generated by Django 2.0.1 on 2018-06-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('florists', '0005_auto_20180617_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bouquet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Name')),
                ('description', models.TextField()),
                ('cli', models.ForeignKey(on_delete='CASCADE', to='florists.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Filters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Text')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete='CASCADE', to='products.Filters')),
            ],
        ),
    ]
