# Generated by Django 2.0.1 on 2018-06-28 13:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bouquet',
            name='filters',
            field=models.ManyToManyField(to='products.Filters'),
        ),
        migrations.AddField(
            model_name='bouquet',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), default=[], size=None),
        ),
        migrations.AddField(
            model_name='bouquet',
            name='max_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bouquet',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Cost'),
        ),
        migrations.AddField(
            model_name='bouquet',
            name='size',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='bouquet',
            name='upprice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Cost'),
        ),
        migrations.AddField(
            model_name='bouquet',
            name='upsize',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='bouquet',
            name='uuid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UUID'),
        ),
    ]
