# Generated by Django 2.0.1 on 2018-06-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180628_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bouquet',
            name='description',
            field=models.CharField(max_length=600, verbose_name='Description'),
        ),
    ]
