# Generated by Django 2.0.1 on 2018-07-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180701_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='bouquet',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
